### ISSUE TITLE
there should be a way to lock the boxes in removing placeholder and make portals into real portals

### ISSUE THREAD

**Issue by baconlover209** [qouteall/MiniScaledMod#1]

**Comment by qouteall** [comment]
What do you mean by "lock the boxes"? The placeholder box is used for tracking whether the box is broken and avoid placing block in that place.

**Comment by baconlover209** [comment]
so that you can change the portals so that they can only be removed by commands and so that they act like portals made by portal helpers

**Comment by qouteall** [comment]
It's being considered

**Comment by baconlover209** [comment]
cool

**Comment by qouteall** [comment]
You can do this by using the command stick of "Make the portal bi-way" to right-click for the 6 outer portals and 6 inner portals. I am not going to add another feature for this as the latest version of MiniScaled supports different-sized scale boxes.
