### ISSUE TITLE
boxes not in miscellaneous tab

### ISSUE THREAD

**Issue by lokzz** [qouteall/MiniScaledMod#11]

**Comment by qouteall** [comment]
Are you sure that you properly installed MiniScaled? Post the log.

**Comment by lokzz** [comment]
not at my computer right now but: 
in the search tab it was there
immersive portal's sticks werent there either
im on 1.19.2

**Comment by qouteall** [comment]
You can install mod menu (mod menu is a mod) to see which mods you installed. Be sure to put the mod into the correct `mods` folder. You can open the game folder via launcher.

**Comment by qouteall** [comment]
Close because outdated.
