### ISSUE TITLE
Crash while inside box.

### ISSUE THREAD

**Issue by lumithespoofy64** [qouteall/MiniScaledMod#16]
Minecraft crashes in a time scale of 3 to 5 seconds of being in the mini box.

**EXIT CODE: 1**

**Comment by qouteall** [comment]
Does this issue occur with only Fabric API and immersive portals and MiniScaled?

**Comment by lumithespoofy64** [comment]
Yes.

**Comment by lumithespoofy64** [comment]
I am using the latest version

**Comment by qouteall** [comment]
Post the crash report to help diagnose the issue. It's in `crash-reports` folder. If there is no crash report, upload the `latest.log` in `logs` folder.

**Comment by lumithespoofy64** [comment]
On it.

**Comment by lumithespoofy64** [comment]
Figured out the problem. I forgot that Gravity API was on. And it broke the game.
