### ISSUE TITLE
Setting spawn in scale boxes

### ISSUE THREAD

**Issue by JustaFloatingEye** [qouteall/MiniScaledMod#21]
You can set your spawn in a scale box, and if you pick up your scale box by blowing it up, you can die and then spawn in the scale box without there being portals. This is game-breaking on servers because now others with scale boxes can go to other people's scale boxes with elytra and fireworks and break into their houses.

You could solve this by teleporting them to spawn or not allowing beds in the scale box dimension.

**Comment by qouteall** [comment]
I see. Will fix.

**Comment by qouteall** [comment]
MiniScaled already allows placing a scale box inside itself. Escaping can even be done without using bed.

I am going to make that ~~when the scale box has no entrance, the inner portals point to the default spawnpoint in overworld~~. And when the player is far from any scale box in `mini_scaled:void` dimension, the player get teleported back to the scale box

**Comment by qouteall** [comment]
Should be fixed in 2.1.1

**Comment by MegaSuperRobloxBoy** [comment]
what did you do to fix it?
