### ISSUE TITLE
when 1.20 😭

### ISSUE THREAD

**Issue by 32smackaroons** [qouteall/MiniScaledMod#29]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

no 1.20 or 1.20.1 i am literally beating my head into a wall right now

**Comment by qouteall** [comment]
There is one version for 1.20.1 https://modrinth.com/mod/miniscaled/version/v3.0.0-mc1.20.1
