### ISSUE TITLE
Unable to leave scaled box from certain faces

### ISSUE THREAD

**Issue by GamyGamer** [qouteall/MiniScaledMod#35]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

I've created scaled box by using /miniscaled command from 0 0 0 to 64 64 64 (or 65, I don't remember exact number I've used but I did use scaling 16)

Next I went inside scaled box and everything looks normal until you try leaving it by facing those ways (relative inside box):
- north
- west
- bottom

Normally you supposed to leave the box into overworld but for some reason I am unable to (just tested it on items/mobs, they leave normally)

While recording video I did use other mods but they have no impact whatsoever, issue is present with only iPortal, MiniScaled and Fabric API present.

https://github.com/iPortalTeam/MiniScaledMod/assets/49346764/603ed439-0e83-41f1-b3ee-66afa4a02cfb

World with this issue:
[Unexpected.zip](https://github.com/iPortalTeam/MiniScaledMod/files/14284350/Unexpected.zip)

Can't send log file as text due to too long message so have a file instead
[latest.log](https://github.com/iPortalTeam/MiniScaledMod/files/14284490/latest.log)

**Comment by qouteall** [comment]
I can reproduce this issue

**Comment by qouteall** [comment]
Should be fixed by this version of iPortal https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v5.1.7-mc1.20.4
