### ISSUE TITLE
Can't find scale boxes in creative inventory in 1.20.4 releases, however can in older releases, such as 1.20.1

### ISSUE THREAD

**Issue by mmdanda** [qouteall/MiniScaledMod#36]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

Whenever I go into the 1.20.4 releases of MiniScaled, I cannot find the scale boxes in the creative inventory, however can still create them with the wand. This problem does not appear in older releases, such as 1.20.1, where I can find them in the creative inventory.
![image](https://github.com/iPortalTeam/MiniScaledMod/assets/163400971/ab6d1d11-11d7-4177-b261-7f4064d8d1f2)

**Comment by qouteall** [comment]
The way of creating scale box has been changed https://qouteall.fun/immptl/wiki/MiniScaled.html

Now you can build a glass frame, use wand to right-click it and wrap it.
