### ISSUE TITLE
Cannot Delete Scaled Box

### ISSUE THREAD

**Issue by MrUnusual** [qouteall/MiniScaledMod#38]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

I didn't see where I can request a feature, but when I started using the mods, I didn't have a full understanding of the stain glass assignments. I used black stain glass to create a scaled box, but it was a test box and I want to delete it now so I can use the same stained glass and same scale size, but I don't see any option to delete it, even on the wiki page. can there be an easy to find option that allows you to delete a scaled box? It probably would be good to put it in the same section where you see "Options", "Get Entrance Item" and "Unwrap", maybe it can be in the "Options"?

**Comment by qouteall** [comment]
Use the wand to right-click on the box then click "unwrap" https://qouteall.fun/immptl/wiki/MiniScaled.html#unwrap
