### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by FullMetalMaster** [qouteall/MiniScaledMod#40]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

manipulation wand just doesn't exist as an item?

### Post the log here

```shell
https://pastebin.com/1mzk4zJG
```

**Comment by qouteall** [comment]
Yes, in 1.18.2 the functionality is different and it has much fewer functionality. It's recommended to use 1.20.4 now.

**Comment by qouteall** [comment]
Unfortunately the 1.18.2 versions are no longer being maintained.

**Comment by FullMetalMaster** [comment]
what about 1.20.1???
