### ISSUE TITLE
Nested portals have really janky collision

### ISSUE THREAD

**Issue by Dual-Iron** [qouteall/MiniScaledMod#5]
Trying to enter a nested portal seems to shunt you back to the overworld under the floor.

https://cdn.discordapp.com/attachments/303638037844197376/942522455988240394/wha_Trim.mp4

**Comment by qouteall** [comment]
Immptl does not yet have two-layer indirect cross portal collision.

**Comment by qouteall** [comment]
ImmPtl now has recursive collision handling. This is probably fixed.
