### ISSUE TITLE
[Request] Please add option to change recipe

### ISSUE THREAD

**Issue by KMFrench1** [qouteall/MiniScaledMod#6]
I would like to request you add a config option to change the nether star to something else. I hate killing the wither, and doing it three time for one of the bigger box's is frustrating.

Please and thank you

**Comment by qouteall** [comment]
The recipe is probably replaceable by a datapack (I am not sure)/
I am also considering changing the recipe. Which ingredient do you suggest?

**Comment by KMFrench1** [comment]
It is not replaceacle via data pack. At least not in a way I know how too do. This is because of how it is coded. It does not do each recipe separately (which is fine, as the current method is nicely coded) but it does a check to see how many nether stars are in recipe then it extrapolates how big the new dimension is base on that. This prevents having tones of recipe Json in the jar. 
As for other recipes, I would do netherite or netherite blocks. They are hard to fine, but don't involve me summoning and killing multiple bosses that destroy terrian.

**Comment by qouteall** [comment]
I think I can make a custom recipe serializer to make this recipe easily changeable by a datapack.

**Comment by KMFrench1** [comment]
that would be nice. Let me know if you do thanks.

**Comment by qouteall** [comment]
I changed that the scale box is now created by using a netherite ingot to right-click a stained glass frame. The old recipe is no longer needed.

**Comment by qouteall** [comment]
Someone suggested changing netherite to other items. I am going to make it configurable
