### ISSUE TITLE
Mobs spawn in boxes when placed

### ISSUE THREAD

**Issue by Toon2400** [qouteall/MiniScaledMod#7]
Mobs Spawn when any scale box is placed, game crashes when set to night time

https://user-images.githubusercontent.com/37460305/162644414-f8b7c733-f003-47bc-a1a1-06264a1feb93.mp4

logs right when i changed time to night and it crashed https://pastebin.com/WVYjVrd1

**Comment by qouteall** [comment]
The mobs comes from the village generation. If an entity falls in the scale box dimension it will be automatically teleported to the nearest scale box. I will disable the village generation

**Comment by qouteall** [comment]
I encountered the crash but cannot stably reproduce it

**Comment by TheCherry** [comment]
Have the same Problem with the villager spawn. And in the dimension are structures from another mods generated. The best thing is at night - then a creeper explode ... everything gets pushed out and the iron golems stucks in the surface ... x)

**Comment by ShockinglySane** [comment]
Any workaround for this? Just started having the same problem last night and can't really load my world. The scale box spawned a Golem and I can hear villagers... villaging for about 3 seconds before it all crashes. I'm going to try getting to the box before it crashes this time...

**Comment by qouteall** [comment]
Probably be fixed in this version https://github.com/qouteall/MiniScaledMod/releases/tag/v1.0.0-1.18.2
